apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet6-postgresql-crud-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet6-postgresql-crud-app
  template:
    metadata:
      labels:
        app: dotnet6-postgresql-crud-app
    spec:
      containers:
      - name: dotnet6-postgresql-crud-app
        image: your-docker-repo/dotnet6-postgresql-crud-app:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: connection-string
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet6-postgresql-crud-app
spec:
  type: ClusterIP
  selector:
    app: dotnet6-postgresql-crud-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
