apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic.config
data:
  newrelic.config: |-
    <?xml version="1.0"?>
    <configuration xmlns="urn:newrelic-config">
        <errorCollector>
            <ignoreStatusCodes>
                <code>400</code>
                <code>401</code>
                <code>403</code>
                <code>404</code>
                <code>405</code>
                <code>406</code>
                <code>409</code>
                <code>412</code>
                <code>415</code>
                <code>451</code>
                <code>422</code>
                <code>429</code>
            </ignoreStatusCodes>
        </errorCollector>
        <transactionEvents maximumSamplesStored="120" />
        <spanEvents maximumSamplesStored="30" />
    </configuration>
